version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: hyper_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-webui:
    image: adminer
    ports:
      - "8081:8080"
    environment:
      ADMINER_DESIGN: pepa-linha-dark
    depends_on:
      - postgres

  hyper-service:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_ADDR=redis:6379
      - POSTGRES_ADDR=postgres:5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hyper_service
    volumes:
      - ./test:/app/test
      - ./configs:/app/configs

volumes:
  redis_data:
  postgres_data:
  